### ISSUE TITLE
Error: config.jobManager.tempFilesPath is required

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#121]
@fvovan @tomaszdurka @vogdb 
```
/usr/lib/node_modules/cm-janus/lib/config.js:117
    throw new Error(result.errors.join(';\n'));
          ^
Error: config.jobManager.tempFilesPath is required
    at Function.Config._validate (/usr/lib/node_modules/cm-janus/lib/config.js:117:11)
    at Config.load (/usr/lib/node_modules/cm-janus/lib/config.js:14:10)
    at Function.Config.createFromFile (/usr/lib/node_modules/cm-janus/lib/config.js:123:10)
    at Object.<anonymous> (/usr/lib/node_modules/cm-janus/bin/cm-janus:8:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by tomaszdurka** [comment]
This is related to our infrastructure puppet modules. For reference: https://github.com/cargomedia/puppet-packages/pull/1094
