### ISSUE TITLE
TCP connection problem

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/cm-janus#158]
```
app error Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
app info Removed Connection{"id":"3891f625-419c-4933-9b0b-c9ea44197a8d"}
app info Added Connection{"id":"a3cc53d0-67b5-4367-83c1-303c24fe36e0"}
app error Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
app debug <- browser {"janus":"create","transaction":"3Ph5T78qvHIW","token":"{\"sessionId\":\"332d91bac894660a3409a631219e8706\"}"}
app info Removed Connection{"id":"a3cc53d0-67b5-4367-83c1-303c24fe36e0"}
app info Added Connection{"id":"f5cceb45-d627-4524-95bd-6d5e0916b8ee"}
app error Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
app info Removed Connection{"id":"f5cceb45-d627-4524-95bd-6d5e0916b8ee"}
app info Added Connection{"id":"370a2223-1132-494d-9b41-f9d9641a23ae"}
```

If I create and destroy sessions in loop I get this error time to time. @tomaszdurka wdyt?

**Comment by kris-lab** [comment]
closing. cannot reproduce anymore.
