### ISSUE TITLE
"null for Plugin...No Stream found for Plugin" error

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm-janus#176]
At some point, the client received this error:
```
{"janus":"error","error":{"code":490,"reason":"Cannot subscribe: null for Plugin{\"id\":2420761243,\"type\":\"janus.plugin.cm.rtpbroadcast\"}error: No Stream found for Plugin{\"id\":2420761243,\"type\":\"janus.plugin.cm.rtpbroadcast\"}"}}
```

Could be related to cargomedia/sk#2780 (2 plugins are detached at the end, which seems wrong), I'll try again when it will be fixed...

WS frames on the client side:
```
{"janus":"attach","plugin":"janus.plugin.cm.rtpbroadcast","transaction":"7p2gsGkET4IX","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767}
{"janus":"success","session_id":995733767,"transaction":"7p2gsGkET4IX","data":{"id":2420761243}}
{"janus":"message","body":{"id":"R0X4rImYFI.1fz1e8aqwHA__","channel_data":"{\"streamChannelType\":269}","request":"watch"},"transaction":"4m8rehtzkt9","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"ack","session_id":995733767,"transaction":"4m8rehtzkt9"}
{"janus":"event","session_id":995733767,"sender":2420761243,"transaction":"4m8rehtzkt9","plugindata":{"plugin":"janus.plugin.cm.rtpbroadcast","data":{"streaming":"event","result":{"stream":{"id":"R0X4rImYFI.1fz1e8aqwHA__","uid":"928a7283b00d76a0adbae438fb1151a7","index":1,"audioport":8817,"videoport":8812,"listeners":1,"waiters":0,"stats":{"min":0,"max":0,"cur":0,"avg":0},"frame":{"width":0,"height":0,"fps":0,"key-distance":0},"session":{"webrtc-active":1,"autoswitch-enabled":1,"remb-avg":0}},"status":"preparing"}}},"jsep":{"type":"offer","sdp":"v=0\r\no=- 1454063275968006 1454063275968006 IN IP4 127.0.0.1\r\ns=CM RTP Broadcast\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS janus\r\nm=audio 1 RTP/SAVPF 111\r\nc=IN IP4 127.0.0.1\r\na=mid:audio\r\na=sendonly\r\na=rtcp-mux\r\na=ice-ufrag:FNDQ\r\na=ice-pwd:ilCqAchn0eax8SNBtopd+p\r\na=ice-options:trickle\r\na=fingerprint:sha-256 85:7E:F6:AD:D1:2B:A7:09:AD:D6:84:DF:19:B1:D5:41:A2:B7:57:50:12:96:EE:E0:A8:A8:68:3D:6F:1A:C3:21\r\na=setup:actpass\r\na=connection:new\r\na=rtpmap:111 opus/48000/2\r\na=ssrc:2067897977 cname:janusaudio\r\na=ssrc:2067897977 msid:janus janusa0\r\na=ssrc:2067897977 mslabel:janus\r\na=ssrc:2067897977 label:janusa0\r\na=candidate:1 1 udp 2013266431 10.0.2.15 57612 typ host\r\na=candidate:2 1 udp 2013266431 10.10.11.10 36490 typ host\r\na=candidate:3 1 udp 2013266431 10.0.3.21 42277 typ host\r\na=candidate:1 2 udp 2013266430 10.0.2.15 51569 typ host\r\na=candidate:2 2 udp 2013266430 10.10.11.10 40929 typ host\r\na=candidate:3 2 udp 2013266430 10.0.3.21 34084 typ host\r\nm=video 1 RTP/SAVPF 100\r\nc=IN IP4 127.0.0.1\r\na=mid:video\r\na=sendonly\r\na=rtcp-mux\r\na=ice-ufrag:mDJZ\r\na=ice-pwd:3FV0Th07svCx8cr13dClLe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 85:7E:F6:AD:D1:2B:A7:09:AD:D6:84:DF:19:B1:D5:41:A2:B7:57:50:12:96:EE:E0:A8:A8:68:3D:6F:1A:C3:21\r\na=setup:actpass\r\na=connection:new\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 goog-remb\r\na=ssrc:2881929246 cname:janusvideo\r\na=ssrc:2881929246 msid:janus janusv0\r\na=ssrc:2881929246 mslabel:janus\r\na=ssrc:2881929246 label:janusv0\r\na=candidate:4 1 udp 2013266431 10.0.2.15 59906 typ host\r\na=candidate:5 1 udp 2013266431 10.10.11.10 43404 typ host\r\na=candidate:6 1 udp 2013266431 10.0.3.21 39340 typ host\r\na=candidate:4 2 udp 2013266430 10.0.2.15 33809 typ host\r\na=candidate:5 2 udp 2013266430 10.10.11.10 60474 typ host\r\na=candidate:6 2 udp 2013266430 10.0.3.21 39514 typ host\r\n"}}
{"janus":"message","body":{"request":"start"},"transaction":"sz1s80WiD2RX","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","jsep":{"type":"answer","sdp":"v=0\r\no=- 953716942312216385 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS\r\nm=audio 9 RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:/oK1JUd2bK2+tkiU\r\na=ice-pwd:8MkVvwSnfvtpJezbCuPKvxaa\r\na=fingerprint:sha-256 0D:68:49:4F:79:C3:76:FB:2E:A4:FF:B6:EA:A2:6B:C4:0D:6C:F8:DF:BF:23:4C:37:BD:27:92:75:8B:2A:7A:D2\r\na=setup:active\r\na=mid:audio\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10; useinbandfec=1\r\na=maxptime:60\r\nm=video 9 RTP/SAVPF 100\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:/oK1JUd2bK2+tkiU\r\na=ice-pwd:8MkVvwSnfvtpJezbCuPKvxaa\r\na=fingerprint:sha-256 0D:68:49:4F:79:C3:76:FB:2E:A4:FF:B6:EA:A2:6B:C4:0D:6C:F8:DF:BF:23:4C:37:BD:27:92:75:8B:2A:7A:D2\r\na=setup:active\r\na=mid:video\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 goog-remb\r\n"},"session_id":995733767,"handle_id":2420761243}
{"janus":"trickle","candidate":{"candidate":"candidate:3472907538 1 udp 2122260223 10.10.11.1 54747 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0},"transaction":"yU2J5ArFhM0u","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"trickle","candidate":{"candidate":"candidate:874861076 1 udp 2122194687 10.0.3.243 54878 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0},"transaction":"f9ZrijopdjfQ","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"ack","session_id":995733767,"transaction":"sz1s80WiD2RX"}
{"janus":"ack","session_id":995733767,"transaction":"yU2J5ArFhM0u"}
{"janus":"ack","session_id":995733767,"transaction":"f9ZrijopdjfQ"}
{"janus":"event","session_id":995733767,"sender":2420761243,"transaction":"sz1s80WiD2RX","plugindata":{"plugin":"janus.plugin.cm.rtpbroadcast","data":{"streaming":"event","result":{"status":"starting"}}}}
{"janus":"event","session_id":995733767,"sender":2420761243,"plugindata":{"plugin":"janus.plugin.cm.rtpbroadcast","data":{"streaming":"event","result":{"status":"stopped"}}}}
{"janus":"trickle","candidate":{"candidate":"candidate:2172887522 1 tcp 1518280447 10.10.11.1 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0},"transaction":"7Pzu6m6hYXiS","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"trickle","candidate":{"candidate":"candidate:2057744100 1 tcp 1518214911 10.0.3.243 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0},"transaction":"LkudV56bgEAI","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"trickle","candidate":{"completed":true},"transaction":"lnHYJwBDG01r","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"ack","session_id":995733767,"transaction":"7Pzu6m6hYXiS"}
{"janus":"ack","session_id":995733767,"transaction":"LkudV56bgEAI"}
{"janus":"ack","session_id":995733767,"transaction":"lnHYJwBDG01r"}
{"janus":"event","session_id":995733767,"sender":2420761243,"plugindata":{"plugin":"janus.plugin.cm.rtpbroadcast","data":{"streaming":"event","result":{"status":"started"}}}}
{"janus":"error","error":{"code":490,"reason":"Cannot subscribe: null for Plugin{\"id\":2420761243,\"type\":\"janus.plugin.cm.rtpbroadcast\"}error: No Stream found for Plugin{\"id\":2420761243,\"type\":\"janus.plugin.cm.rtpbroadcast\"}"}}
{"janus":"detach","transaction":"ChZIBYlZweXI","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":2420761243}
{"janus":"detach","transaction":"vSmVt1KtgF9b","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767,"handle_id":1290498506}
{"janus":"destroy","transaction":"6mXuGnSai5o1","token":"{\"sessionId\":\"790fb6383dd5ed5e642f97d8b7d60bae\"}","session_id":995733767}
{"janus":"detached","session_id":995733767,"sender":2420761243}
{"janus":"error","session_id":995733767,"transaction":"ChZIBYlZweXI","error":{"code":459,"reason":"No such handle 2420761243 in session 995733767"}}
{"janus":"detached","session_id":995733767,"sender":1290498506}
{"janus":"success","session_id":995733767,"transaction":"vSmVt1KtgF9b"}
{"janus":"success","session_id":995733767,"transaction":"6mXuGnSai5o1"}
```

CM Janus log:
```
2016-01-29 10:27:56.142 INFO - http-client request http://localhost:8300/janus/995733767/2420761243 { janus: 'detach', transaction: '5g5feq2ltl' }
2016-01-29 10:27:56.143 INFO - { [Error: Cannot subscribe: null for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}error: No Stream found for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}]
  transaction: undefined,
  code: 490,
  message: 'Cannot subscribe: null for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}error: No Stream found for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}' }
Error: Cannot subscribe: null for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}error: No Stream found for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}
    at /usr/lib/node_modules/cm-janus/lib/janus/plugin/streaming.js:59:13
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/util.js:11:23)
    at /usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:670:18)
    at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:129:16)
    at Async._drainQueues (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:139:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
2016-01-29 10:27:56.144 DEBUG - -> browser { janus: 'error',
  error:
   { code: 490,
     reason: 'Cannot subscribe: null for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}error: No Stream found for Plugin{"id":2420761243,"type":"janus.plugin.cm.rtpbroadcast"}' } }
2016-01-29 10:27:56.147 INFO - http-client response { janus: 'success',
  session_id: 995733767,
  transaction: '5g5feq2ltl' }
```

**Comment by njam** [comment]
Just experienced this on production.
@tomaszdurka what's your take on this?
Is it maybe related to cm-janus restart?

**Comment by tomaszdurka** [comment]
Yes, actually this should be fixed in current master, we just didn't release some time.
Let's keep for reference and verify if it doesn't happen anymore.

**Comment by tomaszdurka** [comment]
I guess this one is closable. @njam ?

**Comment by njam** [comment]
Agree:
```
admin@janus2:~$ zgrep -c 'Cannot subscribe: null for Plugin' /opt/cm-janus-cluster/janus/var/log/cm-janus/*
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.1:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.2.gz:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.3.gz:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.4.gz:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.5.gz:0
/opt/cm-janus-cluster/janus/var/log/cm-janus/cm-janus.log.6.gz:0
```
