### ISSUE TITLE
maxBuffer

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm-janus#194]
@vogdb is this still not released?

```
2016-03-01 10:28:19.400 ERROR - Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:806:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:540:20)
```

**Comment by vogdb** [comment]
Yes. It's not released.
