### ISSUE TITLE
Cannot create mountpoint

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/cm-janus#203]
Could you investigate @tomaszdurka @vogdb 

```
2016-03-08 09:12:21.960 DEBUG - <- janus { janus: 'success',
  session_id: 3625721402,
  sender: 3700375313,
  transaction: 'NKIAURDCBOFHIYIHPXYLDCRM',
  plugindata: 
   { plugin: 'janus.plugin.cm.rtpbroadcast',
     data: 
      { streaming: 'created',
        created: '046D8MQqG3HX4HvjUIMnRg__',
        stream: [Object] } } }
2016-03-08 09:12:21.961 INFO - Added Stream{"id":"53722d85-01ae-4285-88db-97ed66f554e5"} for Plugin{"id":3700375313,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-08 09:12:21.961 INFO - cm-api request https://www.alicex.com/rpc/null { method: 'CM_Janus_RpcEndpoints.publish',
  params: 
   [ 'FqVWLUzZE8swExCfTn5y',
     '{"sessionId":"396293933b218f55f49efce5e728c803"}',
     '046D8MQqG3HX4HvjUIMnRg__',
     '0d5a4eca061b9c74836c53f5d418e931',
     '{"streamChannelType":276}',
     '53722d85-01ae-4285-88db-97ed66f554e5',
     1457428341.961 ] }
2016-03-08 09:12:22.591 ERROR - cm-api response { error: 
   { type: 'CM_Exception_NotAllowed',
     msg: 'Internal server error',
     isPublic: false } }
2016-03-08 09:12:22.593 ERROR - Error: cm-api error: CM_Exception_NotAllowed. Internal server error
    at /usr/lib/node_modules/cm-janus/lib/cm-api-client.js:48:15
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
2016-03-08 09:12:22.595 INFO - cm-api request https://www.alicex.com/rpc/null { method: 'CM_Janus_RpcEndpoints.removeStream',
  params: 
   [ 'FqVWLUzZE8swExCfTn5y',
     '046D8MQqG3HX4HvjUIMnRg__',
     '53722d85-01ae-4285-88db-97ed66f554e5' ] }
2016-03-08 09:12:23.202 INFO - cm-api response undefined
2016-03-08 09:12:23.203 INFO - Removed Stream{"id":"53722d85-01ae-4285-88db-97ed66f554e5"}
2016-03-08 09:12:23.203 INFO - Removed Plugin{"id":3700375313,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-08 09:12:23.203 INFO - Removed Plugin{"id":3700375313,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-08 09:12:23.204 INFO - Removed Session{"id":3625721402}
2016-03-08 09:12:23.204 INFO - Removed [object global]
2016-03-08 09:12:23.204 INFO - Removed Session{"id":3625721402}
2016-03-08 09:12:23.204 INFO - Removed [object global]
2016-03-08 09:12:23.768 INFO - Added Connection{"id":"a66af7b3-cf5a-4539-a534-db81e7d2a430"}
```

cc @njam

**Comment by njam** [comment]
> CM_Exception_NotAllowed: Cannot publish: Not allowed to publish in /home/example/releases/20160307142018/vendor/cargomedia/cm/library/CM/Janus/RpcEndpoints.php on line 64

Closeable?
See https://github.com/cargomedia/sk/issues/3049

**Comment by kris-lab** [comment]
Please ignore this. Resolved already.
